package dao;

import model.Ccscore;
import java.math.BigDecimal;
import java.util.List;

public interface CcscoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CCSCORE
     *
     * @mbggenerated
     */
    int insert(Ccscore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CCSCORE
     *
     * @mbggenerated
     */
    int insertSelective(Ccscore record);

    int add(List<Ccscore> rocord);

    int update(List<Ccscore> rocord);
    List<Ccscore> queryStudent(BigDecimal couid);
}