package dao;

import java.math.BigDecimal;
import model.Ccstudent;

public interface CcstudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CCSTUDENT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal stuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CCSTUDENT
     *
     * @mbggenerated
     */
    int insert(Ccstudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CCSTUDENT
     *
     * @mbggenerated
     */
    int insertSelective(Ccstudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CCSTUDENT
     *
     * @mbggenerated
     */
    Ccstudent selectByPrimaryKey(BigDecimal stuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CCSTUDENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Ccstudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CCSTUDENT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Ccstudent record);

    Ccstudent login(Ccstudent record);
}