package dao;

import java.math.BigDecimal;

import model.Ccstudent;
import model.Ccteacher;

public interface CcteacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CCTEACHER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal teachid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CCTEACHER
     *
     * @mbggenerated
     */
    int insert(Ccteacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CCTEACHER
     *
     * @mbggenerated
     */
    int insertSelective(Ccteacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CCTEACHER
     *
     * @mbggenerated
     */
    Ccteacher selectByPrimaryKey(BigDecimal teachid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CCTEACHER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Ccteacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CCTEACHER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Ccteacher record);

    Ccteacher login(Ccteacher record);
}