package model;

import java.math.BigDecimal;

public class Cccourse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCCOURSE.COUID
     *
     * @mbggenerated
     */
    private BigDecimal couid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCCOURSE.COUNAME
     *
     * @mbggenerated
     */
    private String couname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCCOURSE.TEACHID
     *
     * @mbggenerated
     */
    private BigDecimal teachid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCCOURSE.COUID
     *
     * @return the value of CCCOURSE.COUID
     * @mbggenerated
     */
    public BigDecimal getCouid() {
        return couid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCCOURSE.COUID
     *
     * @param couid the value for CCCOURSE.COUID
     * @mbggenerated
     */
    public void setCouid(BigDecimal couid) {
        this.couid = couid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCCOURSE.COUNAME
     *
     * @return the value of CCCOURSE.COUNAME
     * @mbggenerated
     */
    public String getCouname() {
        return couname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCCOURSE.COUNAME
     *
     * @param couname the value for CCCOURSE.COUNAME
     * @mbggenerated
     */
    public void setCouname(String couname) {
        this.couname = couname == null ? null : couname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCCOURSE.TEACHID
     *
     * @return the value of CCCOURSE.TEACHID
     * @mbggenerated
     */
    public BigDecimal getTeachid() {
        return teachid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCCOURSE.TEACHID
     *
     * @param teachid the value for CCCOURSE.TEACHID
     * @mbggenerated
     */
    public void setTeachid(BigDecimal teachid) {
        this.teachid = teachid;
    }
}