package model;

import java.math.BigDecimal;

public class Ccscore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCSCORE.STUID
     *
     * @mbggenerated
     */
    private BigDecimal stuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCSCORE.COUID
     *
     * @mbggenerated
     */
    private BigDecimal couid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCSCORE.SCORE
     *
     * @mbggenerated
     */
    private BigDecimal score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCSCORE.STUID
     *
     * @return the value of CCSCORE.STUID
     * @mbggenerated
     */
    public BigDecimal getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCSCORE.STUID
     *
     * @param stuid the value for CCSCORE.STUID
     * @mbggenerated
     */
    public void setStuid(BigDecimal stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCSCORE.COUID
     *
     * @return the value of CCSCORE.COUID
     * @mbggenerated
     */
    public BigDecimal getCouid() {
        return couid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCSCORE.COUID
     *
     * @param couid the value for CCSCORE.COUID
     * @mbggenerated
     */
    public void setCouid(BigDecimal couid) {
        this.couid = couid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCSCORE.SCORE
     *
     * @return the value of CCSCORE.SCORE
     * @mbggenerated
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCSCORE.SCORE
     *
     * @param score the value for CCSCORE.SCORE
     * @mbggenerated
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }
}