package model;

import java.math.BigDecimal;
import java.util.List;

public class Ccstudent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCSTUDENT.STUID
     *
     * @mbggenerated
     */
    private BigDecimal stuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCSTUDENT.STUNAME
     *
     * @mbggenerated
     */
    private String stuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CCSTUDENT.PASSWORD
     *
     * @mbggenerated
     */
    private String password;
    /**
     * 学生所选课程的list
     */
    private List<Ccscore> ccscores;

    public List<Ccscore> getCcscores() {
        return ccscores;
    }

    public void setCcscores(List<Ccscore> ccscores) {
        this.ccscores = ccscores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCSTUDENT.STUID
     *
     * @return the value of CCSTUDENT.STUID
     * @mbggenerated
     */
    public BigDecimal getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCSTUDENT.STUID
     *
     * @param stuid the value for CCSTUDENT.STUID
     * @mbggenerated
     */
    public void setStuid(BigDecimal stuid) {
        this.stuid = stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCSTUDENT.STUNAME
     *
     * @return the value of CCSTUDENT.STUNAME
     * @mbggenerated
     */
    public String getStuname() {
        return stuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCSTUDENT.STUNAME
     *
     * @param stuname the value for CCSTUDENT.STUNAME
     * @mbggenerated
     */
    public void setStuname(String stuname) {
        this.stuname = stuname == null ? null : stuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CCSTUDENT.PASSWORD
     *
     * @return the value of CCSTUDENT.PASSWORD
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CCSTUDENT.PASSWORD
     *
     * @param password the value for CCSTUDENT.PASSWORD
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}